### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by t-bltg**
@johnnychen94, I had to merge https://github.com/JuliaImages/XTermColors.jl/pull/1 to setup CI.

If you could review https://github.com/JuliaImages/XTermColors.jl/pull/1, I could release the initial version in https://github.com/JuliaRegistries/General (there is a mandatory period of 3 days), and work on the wrapper `TerminalImages.jl` afterwards.

I you require any changes, I'll push the fixes in this PR.

### CODE REVIEW

**Comment by t-bltg** [comment]
@johnnychen94, ok for initial release ?

**Comment by johnnychen94** [comment]
> @johnnychen94, ok for initial release?

See https://github.com/JuliaImages/XTermColors.jl/pull/3#issue-1269908488, I believe it's easier to use by making `enc` a keyword argument `small_block`.

Also, the color mode stuff seems to belong to TerminalImages where we query the terminal information and provides smart adaptive handling. It's not used here, so might just remove them.

The docstrings also need a revisit before releasing.

**Comment by t-bltg** [comment]
> See https://github.com/JuliaImages/XTermColors.jl/pull/3#issue-1269908488, I believe it's easier to use by making enc a keyword argument small_block.

I don't see how you can do that. We'd need `downscale`, `restrict` and this got removed.

Also I think  `TermColor256` should be renamed to `TermColor8bit` as it is not consistent with `TermColor24bit`.

> Also, the color mode stuff seems to belong to TerminalImages ...

Removed.

**Comment by johnnychen94** [comment]
I think it's because we enforced a canvas concept for `BigBlocks` and `SmallBlocks` and drops out-of-canvas values in https://github.com/JuliaImages/XTermColors.jl/blob/7464534913f5c619b283a4e212062cd9d7bf8986/src/encoder.jl#L133-L141 That should be part of TerminalImages.jl, I believe.

The idea of `XTermColors` is to support a faithfully decoding of the `xterm_24bit_encode` result without knowing the canvas(runtime) information -- if there's `…` in the middle of the encoded result, then we loss the data.

**Comment by johnnychen94** [comment]
> Also I think TermColor256 should be renamed to TermColor8bit as it is not consistent with TermColor24bit.

Maybe, The name `TermColor256` is perhaps based on the observation that most people uses the term "xterm-256 color" instead of "xterm-8bit" for this color setting.

**Comment by johnnychen94** [comment]
Currently busy with other tasks, I can revisit it this weekend if you don't have plans to do the decoding part.

**Comment by t-bltg** [comment]
>  That should be part of TerminalImages.jl, I believe.

I think I'll leave the rewrite in your hands, since I'm afraid my vision on this is kinda blurry.

> Maybe, The name TermColor256 is perhaps based on the observation that most people uses the term "xterm-256 color" instead of "xterm-8bit" for this color setting.

Sure, we know the internals as when taking `8`bits, we can encode `2^8 = 256` colors. What I mean is that since this package is low level it should be imo the other way around and name it with `..._8bit` in the sources and maybe alias it once to `256` for exporting (but I don't think this is necessary, again, since this package is a low level encoder), as it would be more consistent this way.

> Currently busy with other tasks, I can revisit it this weekend if you don't have plans to do the decoding part.

Sure, I have limited time and very few will to do that.

**Pull request closed without merging**
