### PR TITLE
rework `8bit` color encoding

### PR DESCRIPTION
**Pull request by t-bltg**
Superseding https://github.com/JuliaImages/ImageInTerminal.jl/pull/62.
Goes with https://github.com/JuliaImages/ImageInTerminal.jl/pull/68.

```julia
using ImageInTerminal, OffsetArrays, ImageCore

main() = begin
  wheel = OffsetArrays.centered(fill(ARGB(0, 0, 0, 0), (128, 128)))

  for I ∈ CartesianIndices(wheel)
    x, y = I.I ./ (size(wheel) .÷ 2)
    r = sqrt(x^2 + y^2)
    if r < 1
      h = atand(x, y) + 90
      wheel[I] = RGB(HSV(h, r, 1))
    end
  end

  bar = Gray{N0f8}.(repeat(range(0, stop=1, length=64), 1, 2)')

  for enc ∈ (
    ImageInTerminal.XTermColors.TermColor8bit(),
    ImageInTerminal.XTermColors.TermColor24bit()
  )
    @show enc
    display(enc.(wheel))
    display(enc.(bar))
  end
  return
end

main()
```

@johnnychen94 could you tell me if you obtain the same images with this PR ? 

Your graybar image seems better than mine (https://user-images.githubusercontent.com/8684355/147930881-ef076fb5-3252-4d9b-8f00-11a32fa9648f.png), my gradient is not uniform and I have thin dark lines appearing ...

Output with this PR:

**8bit colors**
xtc-24bit

**sixel**
xtc-sixel

### CODE REVIEW

**Comment by johnnychen94** [comment]
FWIW, this is what I get in iTerm (macOS) for this branch, it does look like the gray version is getting worse:

image

**Comment by t-bltg** [comment]
Thanks, I've slightly updated the test script in https://github.com/JuliaImages/XTermColors.jl/pull/5#issue-1330795710.

I've fixed the grayscale issue, here is the output using the 2 color depths (`8bit`, `24bit`), in a `sixel` compatible terminal (`mlterm`):

xc-six

Here is the test script for comparing refs imgs against current master for visual inspection:
```bash
#!/usr/bin/env bash
{
  root="[...]/XTermColors.jl"  # this PR

  for f in $(find $root -path '*/reference/*.txt' | sort -h); do
   tmp=$(mktemp)
   url="https://raw.githubusercontent.com/JuliaImages/XTermColors.jl/master/test/reference/$(basename $f)"
   wget -q -O $tmp $url
   if [ $(wc -c $tmp | awk '{ print $1 }') -eq 0 ]; then
      echo "== disappeared($f) $url =="
      continue
   fi 
   if ! diff $f $tmp 1>/dev/null; then
      echo
      echo "== remote($url) =="
      cat $tmp; echo
      echo "== local($f) =="
      cat $f; echo
    else
      echo "== same($f) =="
   fi
   rm $tmp
  done

  exit
}
```

@johnnychen94, there are some visual changes, so I'm wondering which reference images are better ?

**Review by johnnychen94 — APPROVED** [review]
I'd vote for the PR version. But a few packages use `ImageInTerminal.encode_img` to as test util to compare images, so this will be a breaking change to ImageInTerminal.

**Comment by t-bltg** [comment]
Thanks, this means that we should release `ImageInTerminal` `1.0` instead of `0.5`, right ?

**Comment by johnnychen94** [comment]
1.0 means that API is stable and works. I feel ImageInTerminal is far from stable, e.g., the display, sixel and related are still not well tested.

I personally prefer 0.5, but don't take it too seriously, we have many major release versions to use. Just feel free to make 1.0 release if you like it this way!

**Comment by t-bltg** [comment]
Ha, I mismatched semver again, let's make it `0.5`. I'll merge this now and we can continue discussions in https://github.com/JuliaImages/ImageInTerminal.jl/pull/68.

**Pull request merged**
